

ARG NODE_VERSION=24-alpine

FROM node:${NODE_VERSION} AS base
RUN corepack enable && corepack prepare pnpm@9 --activate
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm build

FROM node:${NODE_VERSION} AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Non-root user (best practice: never run the app as root)
RUN addgroup --system --gid 1001 nodejs \
    && adduser  --system --uid 1001 nextjs

# Only copy what's needed to run the app — Next.js standalone output already
# contains a pruned node_modules and a minimal server entrypoint.
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||3000)).then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

# server.js is generated by Next's standalone output build
CMD ["node", "server.js"]

# ── OCI image labels (best practice metadata) ───────────────────────────────
LABEL org.opencontainers.image.title="k8lens-app" \
    org.opencontainers.image.description="K8sLens — a web UI for browsing and managing Kubernetes clusters" \
    org.opencontainers.image.source="https://github.com/atharvaunde/k8lens-app" \
    org.opencontainers.image.licenses="UNLICENSED" \
    org.opencontainers.image.vendor="Atharva Unde" \
    org.opencontainers.image.authors="hello@atharvaunde.dev" \
    org.opencontainers.image.base.name="docker.io/library/node:24-alpine" \
    org.opencontainers.image.documentation="https://github.com/atharvaunde/k8lens-app/blob/main/README.md"
